'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PrimeReactProvider } from "primereact/api";
const inter = Inter({ subsets: ["latin"] });
import "primeicons/primeicons.css";
// import 'primereact/resources/themes/lara-dark-blue/theme.css';
import Tailwind from "primereact/passthrough/tailwind";
import NavBar from "@/components/menu/NavBar";
import Footer from "@/components/section/Footer";
import { FloatingWhatsApp } from "react-floating-whatsapp";
import logo from "../assets/image/logo/logo.png"
import { Toaster } from "react-hot-toast";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark">
      <body
        className={`${inter.className} w-full h-full overflow-x-hidden text-gray-600 dark:text-gray-300`}
      >
        <PrimeReactProvider value={{ unstyled: true, pt: Tailwind }}>
          <div className="min-h-screen w-full bg-surface-back-white dark:bg-surface-back-black">
            <NavBar />
            {children}
            <Toaster position="bottom-center" />
            <Footer />
            {/* Componente FloatingWhatsApp */}
            <FloatingWhatsApp
              phoneNumber="3704841262"
              accountName="Cloronor"
              chatMessage="Hola 👋, ¿cómo podemos ayudarte?"
              placeholder="Escribe un mensaje..."
              avatar={logo.src}
              statusMessage=""
              notification={true}
              notificationSound={true}
              darkMode={true}
              messageDelay={1}
            />
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
